"""empty message

Revision ID: 85460dcde2d6
Revises: 
Create Date: 2023-07-06 20:33:36.633755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85460dcde2d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
