version: "3.7"

x-logging:
  &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  stock-market-api:
    image: stock-market-api:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    logging: *logging
    init: true
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:12.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    name: pgdata

networks:
  default:
    name: stock_market_net
